# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run:
          name: create tar
          command: tar --exclude=".git" --exclude="node_modules" -czvf ~/wm.tar.gz .
      - add_ssh_keys:
          fingerprints:
            - "f5:4a:23:af:4e:b6:55:9e:69:b6:bb:c4:e3:ce:f1:02"
      - deploy:
          name: nodedeploy
          command: python deploy.py

